# This file was generated by GoReleaser. DO NOT EDIT.
cask "bookmux" do
  name "bookmux"
  desc "A CLI tool for merging audio tracks into M4B audiobooks."
  homepage "https://github.com/MrZoidberg/bookmux"
  version "0.1.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bookmux"

  on_macos do
    on_intel do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Darwin_x86_64.tar.gz"
      sha256 "b2e72420b7dbee545f26e698e6b0ce5c04f25fa00a20e08ed6e452ed36dba93c"
    end
    on_arm do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Darwin_arm64.tar.gz"
      sha256 "040d59114ee752ebb5ca91e5990fe55634b967fe6fcd173da40f533196728f62"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Linux_x86_64.tar.gz"
      sha256 "5ef251a26ee4f9d0358de8b40a65a3cd5e53e009c5a52c3ffb78126037e35522"
    end
    on_arm do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Linux_arm64.tar.gz"
      sha256 "7b3f9257c134e7e8d9c715e457c1478f5efe3312c92f3c6af9dadd02cb434dbd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bookmux"]
    end
  end

  # No zap stanza required
end
