# This file was generated by GoReleaser. DO NOT EDIT.
cask "bookmux" do
  name "bookmux"
  desc "A CLI tool for merging audio tracks into M4B audiobooks."
  homepage "https://github.com/MrZoidberg/bookmux"
  version "0.1.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bookmux"

  on_macos do
    on_intel do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Darwin_x86_64.tar.gz"
      sha256 "21c6d34f0887387d1294347d53079773c36e6eec8f3e78ea3a060308128ad03d"
    end
    on_arm do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Darwin_arm64.tar.gz"
      sha256 "7a1ba453f55968ff939beafbace37f4e44e6a4d46e6bf837bbb468d5c37e88cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Linux_x86_64.tar.gz"
      sha256 "2aae886e1680551f97a8fafc9699f846e52d1d0bd3445b53d784346bdc0f6702"
    end
    on_arm do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Linux_arm64.tar.gz"
      sha256 "02405c382efef2c363727c00592f27a97c850a754a368f998d346618f17ef445"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bookmux"]
    end
  end

  # No zap stanza required
end
