# This file was generated by GoReleaser. DO NOT EDIT.
cask "bookmux" do
  name "bookmux"
  desc "A CLI tool for merging audio tracks into M4B audiobooks."
  homepage "https://github.com/MrZoidberg/bookmux"
  version "0.1.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bookmux"

  on_macos do
    on_intel do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Darwin_x86_64.tar.gz"
      sha256 "f64938b46db7033e3f5720d91be99df58896120d47d3144004d3e4f2ad553d8d"
    end
    on_arm do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Darwin_arm64.tar.gz"
      sha256 "b29cae23e54169b2f97ddbcfe07ce5909ba3f3401083941058bd5e19a8048219"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Linux_x86_64.tar.gz"
      sha256 "3825037b29b4d15c5d6c2d41adeadeba29142fd29e0dc34f5a77e6a2a1548ab9"
    end
    on_arm do
      url "https://github.com/MrZoidberg/bookmux/releases/download/v#{version}/bookmux_#{version}_Linux_arm64.tar.gz"
      sha256 "22dcdb2e6a571af447829094328c140fc5bea2354cd60e9775caab0b85e5aa52"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bookmux"]
    end
  end

  # No zap stanza required
end
